// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWZgmzD3V7pcTXyTVMXBul9WJL6u66gY',
    appId: '1:92134527336:web:ec7bbd4f83309f590dc6dd',
    messagingSenderId: '92134527336',
    projectId: 'notes-app-58fec',
    authDomain: 'notes-app-58fec.firebaseapp.com',
    storageBucket: 'notes-app-58fec.firebasestorage.app',
    measurementId: 'G-8CBZBQ8B1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLejStHKkSrUe5y8xZXbd-5mJ6jyKVi0',
    appId: '1:92134527336:android:f3c9a848d0b6e6d30dc6dd',
    messagingSenderId: '92134527336',
    projectId: 'notes-app-58fec',
    storageBucket: 'notes-app-58fec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATds6YXC8gQJgLX4KZbxWBoxvLIPtGKAs',
    appId: '1:92134527336:ios:a6b74ed35d534a5e0dc6dd',
    messagingSenderId: '92134527336',
    projectId: 'notes-app-58fec',
    storageBucket: 'notes-app-58fec.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATds6YXC8gQJgLX4KZbxWBoxvLIPtGKAs',
    appId: '1:92134527336:ios:a6b74ed35d534a5e0dc6dd',
    messagingSenderId: '92134527336',
    projectId: 'notes-app-58fec',
    storageBucket: 'notes-app-58fec.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpWZgmzD3V7pcTXyTVMXBul9WJL6u66gY',
    appId: '1:92134527336:web:75cf62ab17c690930dc6dd',
    messagingSenderId: '92134527336',
    projectId: 'notes-app-58fec',
    authDomain: 'notes-app-58fec.firebaseapp.com',
    storageBucket: 'notes-app-58fec.firebasestorage.app',
    measurementId: 'G-Z8T20LH86F',
  );
}
